version: '2.2'

volumes:
  postgres_data:
  static:
  media:
  nginx_conf:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  django:
    image: olegenov/yamdb:latest
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    volumes:
      - media:/code/media
      - static:/code/static
      - nginx_conf:/code/nginx
    entrypoint: /code/entrypoint.sh
  nginx:
    build: ./nginx
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - media:/code/media
      - static:/code/static
    depends_on:
      - django
    restart: always
