version: '3.8'

volumes:
  postgres_data:
  static:
  nginx_conf:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  django:
    image: olegenov/yamdb:latest
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    volumes:
      - static:/code/static
      - nginx_conf:/code/nginx/
    entrypoint: /code/entrypoint.sh
  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
    volumes:
      - static:/code/static
      - nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always
