version: '2.2'

volumes:
  postgres_data:
  static:
  media:
  nginx_conf:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  django:
    build: .
    image: olegenov/yamdb:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    volumes:
      - media:/code/media
      - static:/code/static
      - nginx_conf:/code/nginx/
    entrypoint: /code/entrypoint.sh
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - media:/code/media
      - static:/code/static
      - nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always
