# Generated by Django 3.0.5 on 2020-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201116_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.IntegerField(default=7161, verbose_name='Confirmation code'),
        ),
    ]
