# Generated by Django 3.0.8 on 2021-02-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201128_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.IntegerField(default=4179, verbose_name='Confirmation code'),
        ),
    ]
