# Generated by Django 3.0.8 on 2021-02-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210210_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.IntegerField(default=1823, verbose_name='Confirmation code'),
        ),
    ]
